# podman image build...
# podman image build --no-cache --format docker -f Containerfile-pypak-jekyll-srv -t pypak-jekyll-srv .
# podman image build --format docker -f Containerfile-pypak-jekyll-srv -t pypak-jekyll-srv .

# podman rootless...
# ls -al
# podman unshare ls -al .
# podman unshare chown 1000:1000 -R .

# podman unshare ls -al .
# sudo chown alpha:alpha -R .
# podman unshare ls -al .
# ls -al

# podman compose...
# podman unshare chown 1000:1000 -R .
# podman-compose -f docker-compose-project-podman.yml up
# podman container rm levande-landskap

# podman exec...
# podman exec -it 13ab0f32ffe0 /bin/bash

# podman container  run...
# podman container run -it 8f97b35e5316 /bin/bash

# podman-compose -f docker-compose-project-podman.yml up

version: "3"
services:
  jekyll:
    image: pypak-jekyll-srv:v3
    container_name: levande-landskap
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/home/app/srv/jekyll:Z
